import Head from 'next/head'

import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>POC - Use Tailwindcss and custom tokens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1 className='py-4 px-2 font-SemiBold text-6'>Working together with Tailwindcss</h1>
        <div className='bg-electricBlue500 text-samoyed p-2'>test</div>
      </main>
    </>
  )
}
